permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: itfanr
  email: bjq1016@126.com
  link: http://my.oschina.net/itfanr
  weibo: http://weibo.com/itfan
  github: http://github.com/itfanr

# 站点信息
title: itfanr at github
description: itfanr's blog on github
url: http://itfanr.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://itfanr.qiniudn.com/2014-12-28-gavatar.jpg
favicon: http://itfanr.qiniudn.com/2014-12-28-favicon.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
disqus:
  shortname: itfanr

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - 技术


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
